name: Python Setup

on:
  push:
    branches: 
      - '**'  # Trigger on any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Dependency installation
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Show Python version
        run: python --version

      - name: Verify Flake8
        run: flake8 --version

      - name: Verify Pytest
        run: pytest --version

